# Generated by Django 2.0.7 on 2020-10-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('nombre', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_manual', models.TextField()),
            ],
        ),
    ]
